services:
  auth_service:
    build:
      context: ../fast-auth_service
      dockerfile: Dockerfile
    volumes:
      - ../fast-auth_service:/app

  profile_service:
    build:
      context: ../fast-profile_service
      dockerfile: Dockerfile
      secrets:
        - github_token
    volumes:
      - ../fast-profile_service:/app

  content_service:
    build:
      context: ../fast-content_service
      dockerfile: Dockerfile
      secrets:
        - github_token
    volumes:
      - ../fast-content_service:/app

  subscription_service:
    build:
      context: ../fast-subscription_service
      dockerfile: Dockerfile
      secrets:
        - github_token
    volumes:
      - ../fast-subscription_service:/app

  payment_service:
    build:
      context: ../fast-payment_service
      dockerfile: Dockerfile
      secrets:
        - github_token
    volumes:
      - ../fast-payment_service:/app

  frontend:
    build:
      context: ../fast-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8080/api
    volumes:
      - ../fast-frontend:/app

secrets:
  github_token:
    environment: GITHUB_TOKEN
