services:
  auth_service:
    build:
      context: ../fastboosty-auth_service
      dockerfile: Dockerfile
    volumes:
      - ../fastboosty-auth_service:/app

  profile_service:
    build:
      context: ../fastboosty-profile_service
      dockerfile: Dockerfile
      secrets:
        - github_token
    volumes:
      - ../fastboosty-profile_service:/app

  content_service:
    build:
      context: ../fastboosty-content_service
      dockerfile: Dockerfile
      secrets:
        - github_token
    volumes:
      - ../fastboosty-content_service:/app

  subscription_service:
    build:
      context: ../fastboosty-subscription_service
      dockerfile: Dockerfile
      secrets:
        - github_token
    volumes:
      - ../fastboosty-subscription_service:/app

  payment_service:
    build:
      context: ../fastboosty-payment_service
      dockerfile: Dockerfile
      secrets:
        - github_token
    volumes:
      - ../fastboosty-payment_service:/app

  frontend:
    build:
      context: ../fastboosty-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8080/api
    volumes:
      - ../fastboosty-frontend:/app

secrets:
  github_token:
    environment: GITHUB_TOKEN
